---
title: "Simple Simulation Illustration"
author: "Florian Stijven"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
set.seed(1)
```

```{r}
library(tidyverse)
library(sandwich)
library(lmtest)
```


```{r}
# Source functions for the moment-based estimator
source(here::here("R", "helper-functions", "moment-based-estimator.R"))
source(here::here("R", "helper-functions", "delta-method-rho-trial.R"))
source(here::here("R", "helper-functions", "multiplier-bootstrap.R"))
# Source functions to simulate data
source(here::here("R", "helper-functions", "simulation-functions.R"))

# Function to train the clinical prediction model and return prediction function.
train_clinical_prediction_model <- function(simulated_data) {
  # Train a correctly specified linear regression model for predicting the
  # clinical endpoint given the surrogate and baseline covariate
  clinical_model <- lm(clinical ~ surrogate * covariate + surrogate ^ 2, data = simulated_data)

  return(
    function(newdata) {
      return(predict(clinical_model, newdata = newdata))
    }
  )
}
```


# Illustration of Simulated data

## Individual-Patient Data

```{r}
# Generate IPD for a meta-analytic setting
ma_ipd_tbl = simulate_trials_with_random_coefficients(
  N = 10,
  n = 2e3,
  sd_beta_clin_surrogate_sq = 0.10,
  sd_beta_clin_treatment = 0.10
)
# Estimate "predcition model", which is just a correctly specified linear
# regression model.
surr_index_pred_f = train_clinical_prediction_model(ma_ipd_tbl)
# Add surrogate indew to IPD data
ma_ipd_tbl$surr_index = surr_index_pred_f(ma_ipd_tbl)
```

```{r}
# Plot the surrogate against the clinical endpoint.
ma_ipd_tbl %>%
  ggplot(aes(x = surrogate, y = clinical, color = as.factor(covariate))) +
  geom_point(alpha = 0.1) +
  facet_wrap("trial")
```

```{r}
# Plot the surrogate index against the clinical endpoint.
ma_ipd_tbl %>%
  ggplot(aes(x = surr_index, y = clinical)) +
  geom_point(alpha = 0.1) +
  geom_smooth(aes(group = as.factor(trial))) +
  facet_wrap("trial") +
  geom_abline(intercept = 0, slope = 1)
```


## Trial-Level Treatment Effects

```{r}
ma_trt_effect_tbl = ma_ipd_tbl %>%
  group_by(trial) %>%
  reframe(compute_treatment_effects(pick(everything()))) %>%
  ungroup()

ma_trt_effect_index_tbl = ma_ipd_tbl %>%
  select(-surrogate) %>%
  rename(surrogate = surr_index) %>%
  group_by(trial) %>%
  reframe(compute_treatment_effects(pick(everything()))) %>%
  ungroup()
```

```{r}
# Create a scatter plot with treatment effects on surrogate vs. clinical, including 95% CI error bars
ggplot(ma_trt_effect_tbl, aes(x = treatment_effect_surr, y = treatment_effect_clin)) +
  # Scatter plot of treatment effects
  geom_point() +
  # Horizontal error bars for surrogate treatment effect
  geom_errorbarh(aes(xmin = treatment_effect_surr - 1.96 * se_surr, 
                     xmax = treatment_effect_surr + 1.96 * se_surr), 
                 height = 0.05) +
  # Vertical error bars for clinical treatment effect
  geom_errorbar(aes(ymin = treatment_effect_clin - 1.96 * se_clin, 
                    ymax = treatment_effect_clin + 1.96 * se_clin), 
                width = 0.05) +
  # Labels and title
  labs(
    x = "Treatment Effect on Surrogate Endpoint",
    y = "Treatment Effect on Clinical Endpoint",
    title = "Treatment Effects on Surrogate vs. Clinical Endpoint with 95% Confidence Intervals"
  ) 
```

```{r}
# Create a scatter plot with treatment effects on surrogate vs. clinical, including 95% CI error bars
ggplot(ma_trt_effect_index_tbl, aes(x = treatment_effect_surr, y = treatment_effect_clin)) +
  # Scatter plot of treatment effects
  geom_point() +
  # Horizontal error bars for surrogate treatment effect
  geom_errorbarh(aes(xmin = treatment_effect_surr - 1.96 * se_surr, 
                     xmax = treatment_effect_surr + 1.96 * se_surr), 
                 height = 0.05) +
  # Vertical error bars for clinical treatment effect
  geom_errorbar(aes(ymin = treatment_effect_clin - 1.96 * se_clin, 
                    ymax = treatment_effect_clin + 1.96 * se_clin), 
                width = 0.05) +
  # Labels and title
  labs(
    x = "Treatment Effect on Estimated Surrogate Index",
    y = "Treatment Effect on Clinical Endpoint",
    title = "Treatment Effects on Surrogate vs. Clinical Endpoint with 95% Confidence Intervals"
  ) +
  geom_abline(intercept = 0, slope = 1)
```

## Moment-Based Estimator

```{r}
# Estimate the meta-analytic parameters using the moment-based estimator.
moment_estimator_tbl = tibble(
  setting = c("surrogate", "surrogate index"),
  data = list(ma_trt_effect_tbl, ma_trt_effect_index_tbl)
) %>%
  cross_join(expand_grid(
    estimator_adjustment = c("none", "N - 1"),
    sandwich_adjustment = c("none", "N - 1")
  )) %>%
  rowwise(everything()) %>%
  summarise(
    moment_estimate = list(
      moment_estimator(
        data$treatment_effect_surr,
        data$treatment_effect_clin,
        data$covariance_matrix,
        estimator_adjustment = estimator_adjustment,
        sandwich_adjustment = sandwich_adjustment
      )
    ),
    rho_est = list(
      rho_delta_method(coefs = moment_estimate$coefs, vcov = moment_estimate$vcov)
    )
  ) %>%
  ungroup() %>%
  mutate(
    rho = purrr::map_dbl(rho_est, "rho"),
    se = purrr::map_dbl(rho_est, "se"),
    lower_ci = purrr::map_dbl(rho_est, c(3, 1)),
    upper_ci = purrr::map_dbl(rho_est, c(3, 2))
  )
```

```{r}
statistic_function_factory = function(estimator_adjustment) {
  statistic_f = function(data, weights) {
    moment_estimate = moment_estimator(
      alpha_hat = data$treatment_effect_surr,
      beta_hat = data$treatment_effect_clin,
      vcov_list = data$covariance_matrix,
      estimator_adjustment = estimator_adjustment,
      weights = weights
    )
    rho_est = rho_delta_method(moment_estimate$coefs, moment_estimate$vcov)
    
    return(rho_est$rho)
  }
  return(statistic_f)
}


moment_estimator_tbl = bind_rows(
    moment_estimator_tbl %>%
      mutate(CI = "sandwich"),
    moment_estimator_tbl %>%
      filter(sandwich_adjustment == "none") %>%
      rowwise(everything()) %>%
      summarise(
        bootstrap_ci = list(multiplier_bootstrap_ci(
          data = data,
          statistic = statistic_function_factory(estimator_adjustment),
          B = 1e3
        )),
        lower_ci = bootstrap_ci$ci_lower,
        upper_ci = bootstrap_ci$ci_upper
      ) %>%
      ungroup() %>%
      mutate(CI = "multiplier bootstrap")
  )

```


```{r}
# Present results with simulated data set in a tibble.
moment_estimator_tbl %>%
  select(-data, -moment_estimate, -rho_est, -bootstrap_ci) %>%
  knitr::kable(digits = 3)
```

```{r}
# Visualize the computed confidence intervals.
moment_estimator_tbl %>%
  ggplot(aes(x = rho, color = estimator_adjustment, y = CI, linetype = sandwich_adjustment)) +
  geom_point(position = position_dodge(width = 0.2)) +
  geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci), height = 0.1, position = position_dodge(width = 0.2)) +
  xlim(c(-1.2, 1.2)) +
  facet_grid(. ~ setting)
```


# Simulation Results

```{r}
# Read in simulation results.
meta_analytic_data_simulated <- readRDS(
  here::here(
    "results",
    "raw-results",
    "simple-simulation",
    "meta_analytic_data_simulated.rds"
  )
)
```

```{r}
# Distribution of data-adaptive rho-trial estimands (approximated through MC
# integration).
meta_analytic_data_simulated %>%
  filter(analysis_type == "surrogate index") %>%
  ggplot(aes(x = rho_true)) +
  geom_histogram() +
  facet_grid(.~sd_beta_clin_treatment)
```


```{r}
# Compute coverage, mean bias, median bias, empirical SD, and mean SE.
simulations_summary_tbl = meta_analytic_data_simulated %>%
  group_by(analysis_type, sd_beta_clin_surrogate_sq, sd_beta_clin_treatment, estimator_adjustment, sandwich_adjustment, CI_type) %>%
  summarise(
    coverage = mean((rho_true >= rho_ci_lower) & (rho_true <= rho_ci_upper), na.rm = TRUE),
    mean_bias = mean(rho_est - rho_true, na.rm = TRUE),
    median_bias = median(rho_est - rho_true, na.rm = TRUE),
    emp_SD = sd(rho_est, na.rm = TRUE),
    mean_SE = mean(rho_se, na.rm = TRUE),
    MSE = mean((rho_true - rho_est) ^2, na.rm = TRUE)
  )
```

```{r}
simulations_summary_tbl  %>%
  knitr::kable(digits = 3)
```


```{r}
simulations_summary_tbl %>%
  ggplot(aes(x = CI_type, y = coverage, color = estimator_adjustment, shape = sandwich_adjustment)) +
  geom_point(position = position_dodge(width = 0.1)) +
  ylim(c(0.80, 1)) +
  geom_abline(intercept = 0.95, slope = 0) +
  facet_grid(sd_beta_clin_treatment~analysis_type)
```

```{r}
simulations_summary_tbl %>%
  filter(CI_type == "sandwich", sandwich_adjustment == "none") %>%
  ggplot(aes(x = CI_type, y = mean_bias, color = estimator_adjustment, shape = sandwich_adjustment)) +
  geom_point(position = position_dodge(width = 0.1)) +
  geom_abline(intercept = 0, slope = 0) +
  ylim(c(-0.05, 0.05)) +
  facet_grid(sd_beta_clin_treatment~analysis_type)
```

```{r}
simulations_summary_tbl %>%
  filter(CI_type == "sandwich", sandwich_adjustment == "none") %>%
  ggplot(aes(x = CI_type, y = MSE, color = estimator_adjustment, shape = sandwich_adjustment)) +
  geom_point(position = position_dodge(width = 0.1)) +
  geom_abline(intercept = 0, slope = 0) +
  ylim(c(0, 0.25)) +
  facet_grid(sd_beta_clin_treatment~analysis_type)
```





Distribution of lower limits of the bootstrap CIs across the scenarios.

```{r}
meta_analytic_data_simulated %>%
  filter(CI_type == "multiplier bootstrap") %>%
  ggplot(aes(x = rho_ci_lower, fill = analysis_type)) +
  geom_histogram(position = "identity", alpha = 0.5, color = "black") +
  xlim(c(-1, 1)) +
  facet_grid(estimator_adjustment~sd_beta_clin_treatment)
```

Distribution of upper limits of the bootstrap CIs across the scenarios.

```{r}
meta_analytic_data_simulated %>%
  filter(CI_type == "multiplier bootstrap") %>%
  ggplot(aes(x = rho_ci_upper, fill = analysis_type)) +
  geom_histogram(position = "identity", alpha = 0.5, color = "black") +
  xlim(c(-1, 1.5)) +
  facet_grid(estimator_adjustment~sd_beta_clin_treatment)
```

